### ISSUE TITLE
Attach "Today" to a channel/systemvariable

### ISSUE THREAD

**Issue by Goersch** [Pix---/ioBroker.feiertage#15]
Hello, 
would be very helpful if I could connect the state of "today"/"heute" with a channel or systemvariable. Would make this add-on much more helpful.
Georg

**Comment by Pix---** [comment]
Hello Georg,
could you specify your suggestion?
Or do you mean this?
`on("feiertage.0.today", "systemvariable"); // on change sync today with systemvariable`

**Comment by Goersch** [comment]
yes, thats what I mean - I know, I can do it with a script - but it would be easier to have it within the setup for "feiertage" especially for people who do not wanz to deal with scripts

**Comment by Pix---** [comment]
Can you explain for which purpose someone would use a Systemvariable instead of the original adapter's datapoint "today"?

**Comment by Goersch** [comment]
I would like to use the systemvariable within the programs on the CCU. Right now this is already done by a script - but, I'm running out of variables (max 200) and this script is using a lot of them. So I would like the Feiertage calculation being done in iobroker and the  result used on the CCU.

:) of course I can add the script to iobroker. But I thought making things easy is a good idea for people who cannot or don't want to deal with scripts in iobroker :)

**Comment by Pix---** [comment]
I think this feature would be to special. I do not see the benefit.
