### ISSUE TITLE
v1.0.2 und v.1.03 installiert sich nicht

### ISSUE THREAD

**Issue by BramTown** [Pix---/ioBroker.feiertage#20]
Moin Pix, 

heute kamen kurz nacheinander die v1.0.1 und die v1.0.2 raus
Während sich die v1.0.1 problemlos installieren ließ, will mir das mit der v1.0.2 nicht gelingen.

Ich habe das Update nun bereits 4 x angestossen, nach dem Schließen des Fensters wird mir aber weiterhin die v1.0.1 angezeigt,  mit dem Hinweis auf eine neuere v1.02.

Ciao und Gruß,
Heiko

**Comment by BramTown** [comment]
nachstehend das log-file
`iobroker | 2018-04-21 22:27:47.946 | info | Adapter "feiertage" updated
-- | -- | -- | --
iobroker | 2018-04-21 22:27:47.881 | info | upload [0] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/feiertage.png feiertage.png image/png
iobroker | 2018-04-21 22:27:47.815 | info | upload [1] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/holidays.js holidays.js application/javascript
iobroker | 2018-04-21 22:27:47.746 | info | upload [2] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/de/flat.txt i18n/de/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.680 | info | upload [3] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/en/flat.txt i18n/en/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.615 | info | upload [4] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/es/flat.txt i18n/es/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.555 | info | upload [5] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/flat.txt i18n/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.495 | info | upload [6] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/fr/flat.txt i18n/fr/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.404 | info | upload [7] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/it/flat.txt i18n/it/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.273 | info | upload [8] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/nl/flat.txt i18n/nl/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.205 | info | upload [9] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/pl/flat.txt i18n/pl/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.139 | info | upload [10] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/pt/flat.txt i18n/pt/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.076 | info | upload [11] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/i18n/ru/flat.txt i18n/ru/flat.txt text/plain
iobroker | 2018-04-21 22:27:47.015 | info | upload [12] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/index.html index.html text/html
iobroker | 2018-04-21 22:27:46.952 | info | upload [13] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/index_m.html index_m.html text/html
iobroker | 2018-04-21 22:27:46.876 | info | upload [14] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/words.js words.js application/javascript
iobroker | 2018-04-21 22:27:46.827 | info | got /opt/iobroker/node_modules/iobroker.feiertage/admin
iobroker | 2018-04-21 22:27:32.265 | info | npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.feiertage"
iobroker | 2018-04-21 22:27:32.196 | info | optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
iobroker | 2018-04-21 22:27:32.192 | info | npm WARN
iobroker | 2018-04-21 22:27:32.192 | info | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):
iobroker | 2018-04-21 22:27:32.192 | info | WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connecti
iobroker | 2018-04-21 22:27:32.189 | info | npm
iobroker | 2018-04-21 22:27:14.625 | info | gyp ERR! not ok
iobroker | 2018-04-21 22:27:14.625 | info | gyp ERR! node-gyp -v v3.4.0
iobroker | 2018-04-21 22:27:14.625 | info | gyp ERR! node -v v6.14.1
iobroker | 2018-04-21 22:27:14.625 | info | gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
iobroker | 2018-04-21 22:27:14.625 | info | ERR! System Linux 4.9.65-v7+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
iobroker | 2018-04-21 22:27:14.622 | info | gyp
iobroker | 2018-04-21 22:27:14.622 | info | gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
iobroker | 2018-04-21 22:27:14.622 | info | gyp ERR! stack at ChildProcess.emit (events.js:191:7)
iobroker | 2018-04-21 22:27:14.622 | info | gyp ERR! stack at emitTwo (events.js:106:13)
iobroker | 2018-04-21 22:27:14.622 | info | ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
iobroker | 2018-04-21 22:27:14.619 | info | gyp
iobroker | 2018-04-21 22:27:14.614 | info | ERR! build error
iobroker | 2018-04-21 22:27:14.607 | info | gyp
iobroker | 2018-04-21 22:27:14.600 | info | make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Error 1
iobroker | 2018-04-21 22:27:13.300 | info | compilation terminated.
iobroker | 2018-04-21 22:27:13.296 | info | ^
iobroker | 2018-04-21 22:27:13.296 | info | ../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include
iobroker | 2018-04-21 22:25:50.745 | info | npm install iobroker.feiertage@1.0.2 --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2018-04-21 22:25:49.598 | info | NPM version: 3.10.10
iobroker | 2018-04-21 22:25:48.442 | info | Update feiertage from @1.0.1 to @1.0.2
iobroker | 2018-04-21 22:25:45.853 | info | upgrade feiertage

`

**Comment by FabianHM** [comment]
Bei mit laässt sich die V 1.0.2 auch nicht installieren. Die Version steht ständig zur Installation an.
Die Auswahlcheckbocen der Feiertage sind auch verschwunden.

**Comment by Pix---** [comment]
Ich bin zur Zeit in Kassel beim HM-Usertreffen. 
Eine neue Version 1.0.3 liegt hier bereits zur manuellen Installation bereit.

Wenn ich das obige Log richtig interpretiere, hat es was mit den Dependencies zu tun. Die Auswahl der Dependencies wird in der Anleitung zum Upgrade der Adapter auf Admin3-Fähigkeit vorgegegen. Mit diesen Auswirkungen konnte ich nicht rechnen.

Auf npm werde ich natürlich erst wieder publishen, wenn es keine Probleme mehr gibt. Frühestens aber erst, wenn ich wieder zu Hause bin.

**Comment by BramTown** [comment]
Moin Pix,

gar kein Grund zur Eile, ich wollte dich auch lediglich informieren, und wenn Du eine Idee hast woher das kommt, dann passt das ja!

... der nächste Feiertag ist sowieso erst der 1 Mai, und denn kennt ioBoker bereits 😁 

viel Spaß in Kassel!!
Ciao udn Gruß,
Heiko

**Comment by BramTown** [comment]
mit der v1.0.3 ändert sich das Fehlerbild:
`$ ./iobroker add feiertage 
ERROR: module.js:597    throw err;
    ^

SyntaxError: /opt/iobroker/node_modules/iobroker.feiertage/io-package.json: Unexpected token < in JSON at position 1841
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:594:27)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:219:23)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:712:24
    at Socket.objects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:391:57)

ERROR: process exited with code 1`

**Comment by BramTown** [comment]
sowie:
`Fertig mit Fehler: module.js:597 throw err; ^ SyntaxError: /opt/iobroker/node_modules/iobroker.feiertage/io-package.json: Unexpected token < in JSON at position 1841 at Object.parse (native) at Object.Module._extensions..json (module.js:594:27) at Module.load (module.js:494:32) at tryModuleLoad (module.js:453:12) at Function.Module._load (module.js:445:3) at Module.require (module.js:504:17) at require (internal/module.js:20:19) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:219:23) at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:712:24 at Socket.objects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:391:57)`

**Comment by BramTown** [comment]
Moin Pix,

Nachtrag:
- In der Adapter-Übersicht wurde mir keine installierte Instanz angezeigt
- über das "+" Symbol konnte ich ich keine Instanz installieren die vorherige Fehlermeldung erscheint reproduzierbar, aber keine installierte Instanz verfügbar
- daher auch keine Deinstallation möglich (kein Papierkorb Symbol)
- Installation über Github (von beliebige URL) schafte dann allerdings Abhilfe.

Somit habe ich derzeit die v1.0.3 erfolgreich installiert bekommen.
