### ISSUE TITLE
"./iobroker upgrade" throws error with version 1.0.3

### ISSUE THREAD

**Issue by cernst1980** [Pix---/ioBroker.feiertage#21]
ERROR: module.js:674    throw err;
    ^

SyntaxError: /usr/local/www/iobroker/node_modules/iobroker.feiertage/io-package.json: Unexpected token < in JSON at position 1841
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Upgrade.upgradeAdapter (/usr/local/www/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:169:27)
    at Upgrade.upgradeAdapterHelper (/usr/local/www/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:32:14)
    at Immediate._onImmediate (/usr/local/www/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:40:26)

ERROR: process exited with code 1

**Comment by GermanBluefox** [comment]
It is wrong file in the package
![image](https://user-images.githubusercontent.com/4582016/39275950-890ad7f2-48e7-11e8-83cd-e9abc907811e.png)
@Pix--- please fix asap

**Comment by Pix---** [comment]
This issue has been fixed 4 days ago.
![bildschirmfoto 2018-04-26 um 00 55 34](https://user-images.githubusercontent.com/8090989/39277148-a5262612-48ec-11e8-8e43-63070f762f74.jpg)
![bildschirmfoto 2018-04-26 um 00 55 55](https://user-images.githubusercontent.com/8090989/39277149-a5440588-48ec-11e8-9a73-15dfe5fd5576.jpg)

**Comment by GermanBluefox** [comment]
Aber du musst publishen. Auf npm ist alte Version. Also Version erhöhen und
noch mal npm publish

чт, 26 апр. 2018 г., 0:58 Pix <notifications@github.com>:

**Comment by Pix---** [comment]
A new version of the package iobroker.feiertage (1.0.4) was published at 2018-04-26T07:52:15.424Z

**Comment by FabianHM** [comment]
Hallo, nach den Problemen seit der Version 1.0.2 hatte ich den Adapter komplett entfernt.
Beim aktuellen Versuch die 1.0.4 zu installieren kommt folgende Fehlermeldung. Auch eine ältere Versionlässt sich nicht mehr installieren.
**_Fertig mit Fehler: module.js:597 throw err; ^ SyntaxError: /opt/iobroker/node_modules/iobroker.feiertage/io-package.json: Unexpected token < in JSON at position 1841 at Object.parse (native) at Object.Module._extensions..json (module.js:594:27) at Module.load (module.js:494:32) at tryModuleLoad (module.js:453:12) at Function.Module._load (module.js:445:3) at Module.require (module.js:504:17) at require (internal/module.js:20:19) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:220:23) at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:611:24 at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:394:57)_**
Grüße
Fabian

**Comment by GermanBluefox** [comment]
Ich habe gerade versucht 1.0.4 zu installieren und bei mir hat es geklappt. Es scheint, so als ob 1.0.3 bei dir ist.

**Comment by FabianHM** [comment]
Komisch, ich habe zumindest die 1.0.3 nie geschaft korrekt zu installieren. was kann ich tun? Reboot brachte nix....

**Comment by cernst1980** [comment]
Ich musste 1.0.4 direkt aus github installieren, dann klappte es ohne Fehlermeldung
