### ISSUE TITLE
Scrollbar in Config Screen fehlt

### ISSUE THREAD

**Issue by Scrounger** [Pix---/ioBroker.feiertage#26]
Es gibt keine Scrollbra im Config Screen beim Admin v3. Somit kann man auch die Feiertage nicht auswählen.

**Comment by Pix---** [comment]
Hallo,
ich kann den Fehler nicht reproduzieren. Scrollbar ist vorhanden und funktioniert (siehe Anhang). Welcher Browser macht Probleme?

![scrollbar_settings](https://user-images.githubusercontent.com/8090989/43636752-42ff9854-9713-11e8-8f8b-ea1861f0575a.gif)

**Comment by Scrounger** [comment]
Perfekt jetzt gehts, danke!
