### ISSUE TITLE
Nationalfeiertag Österreich

### ISSUE THREAD

**Issue by JohGrei** [Pix---/ioBroker.feiertage#31]
Hallo, ist es möglich den 26.10 ist der Nationalfeiertag in Österreich zu den Feiertagen hinzuzufügen.

**Comment by Pix---** [comment]
Danke für den Hinweis. Ist integriert. Lade 1.0.9 von Github. Nach einer Testphase wird die Version im ioBroker Repository aufgenommen.

**Comment by JohGrei** [comment]
Danke für die flotte Umsetzung
