### ISSUE TITLE
Bitte 2 Feiertage für Österreich hinzufügen

### ISSUE THREAD

**Issue by Schatn** [Pix---/ioBroker.feiertage#35]
Hallo! Bitte Christi Himmelfahrt und Pfingsmontag für Österreich hinzufügen. Danke

**Comment by Pix---** [comment]
Christi Himmelfahrt und Pfingstmontag sind bereits seit der ersten Version eingebaut. Hier ein Screenshot: 
![bildschirmfoto 2018-11-03 um 15 37 53](https://user-images.githubusercontent.com/8090989/47953479-7fee5800-df7e-11e8-9479-68535832571e.jpg)

**Comment by Pix---** [comment]
Aktuelle Version ist 1.0.11. Habe sie heute für das stable-Repo vorgeschlagen, sollte die Tage dann die alte 1.0.0 ersetzen.
