### ISSUE TITLE
Datum nächster Feiertag (Neujahr) wird falsch angezeigt

### ISSUE THREAD

**Issue by Steff42** [Pix---/ioBroker.feiertage#36]
Hallo,
heute morgen (26.12.2018) habe ich die Anzeige des nächsten Feiertags (Neujahr) gesehen, dort wird anstatt 01.01.2019 der 01.01.2018 angezeigt. Siehe Bild:
![image](https://user-images.githubusercontent.com/35137293/50439010-9f579080-08f0-11e9-9d0d-28f14a1c7ae4.png)
Gruß Steffen
feiertage-Version 1.0.11

**Comment by Baenker** [comment]
@Pix--- nach meiner Meinung könnte hier zu gemacht werden. Es gab dazu ja bereits ein fix....

Änderung Jahreszahl bei neuem Jahr #47
