### ISSUE TITLE
Weltkindertag in Thüringen

### ISSUE THREAD

**Issue by stsch83** [Pix---/ioBroker.feiertage#42]
bitte den Weltkindertag als Feiertag in Thüringen (immer am 20.09.) hinzufügen

**Comment by Pix---** [comment]
Erledigt mit v1.0.12. [Weltkindertag ist seit 2019 Feiertag in Thüringen](https://www.feiertage-deutschland.de/weltkindertag/)

**Comment by stsch83** [comment]
Hallo,

wann steht die Version 1.0.12 zur verfügung ?

Am Mo., 26. Aug. 2019 um 09:00 Uhr schrieb Pix <notifications@github.com>:

**Comment by Pix---** [comment]
Steht zum Test zu Verfügung. Stable erst nach Test. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stsch83** [comment]
Hallo,

ich habe die v1.0.12 installiert und getestet. leider kann ich den 20.9.
nicht in der Auswahlliste finden.

Am Fr., 30. Aug. 2019 um 12:09 Uhr schrieb Pix <notifications@github.com>:

**Comment by Pix---** [comment]
Danke für das Feedback. Ich habe bei mir keine Probleme (Siehe Screenshot)
![Bildschirmfoto 2019-08-30 um 23 50 28](https://user-images.githubusercontent.com/8090989/64053084-39a75c80-cb81-11e9-8810-241c43744345.jpg)

Nach der Installation aus Github muss der Hochladen-Knopf (roter Kreis) gedrückt werden. Ich denke, das hilft.

![Bildschirmfoto 2019-08-30 um 23 50 46](https://user-images.githubusercontent.com/8090989/64053118-652a4700-cb81-11e9-8436-6f61c1a9fb06.jpg)


Gruß
Pix

**Comment by stsch83** [comment]
Danke, das war es gewesen.

Funktioniert. Top.

**Comment by stsch83** [comment]
Meine Instanz zeigt an das Heute Weltkindertag ist !?!?

**Comment by stsch83** [comment]
Hallo,

es wird leider nicht angezeigt dass morgen Feiertag in Thüringen ist. Bereits am 11.9. wurde falsch angezeigt das Weltkindertag in Thüringen ist. Es soll aber erst morgen (20.9.) Feiertag in Thüringen sein.

Mfg
Stefan

**Comment by Pix---** [comment]
Hallo Stefan,
habe nochmal den Code geprüft und falsche Offset-Angaben gefunden. Sollte jetzt passen.

Gruß
Pix

**Comment by Pix---** [comment]
Neue Version 1.0.13 bitte manuell in Admin laden und Hochladen-Knopf nicht vergessen.

**Comment by stsch83** [comment]
Danke. Scheint jetzt zu funktionieren.
