### ISSUE TITLE
Nationalfeiertag Schweiz 

### ISSUE THREAD

**Issue by jsail** [Pix---/ioBroker.feiertage#45]
Bitte fügt den 1. August auch noch zum FeiertagAngebot.
Dank und Gruss
Sepp

**Comment by Pix---** [comment]
Hallo Sepp,
danke für die Anregung. Versuch die Version 1.0.14
Wenn alles klappt, bitte ich um Rückmeldung. Kann dann mal wieder was ins Stable verschieben.

Pix
