### ISSUE TITLE
Neujahrstag

### ISSUE THREAD

**Issue by Kampfratte** [Pix---/ioBroker.feiertage#46]
Hallo,

wir haben heute den 31.12.2019 und morgen wäre der 1.1.20. Der Adapter hat mir aber als nächsten Feiertag in 1 Tag den 01.01.19 in geschrieben.

**Comment by Kampfratte** [comment]
zudem wird hier im Changelog die Version 1.0.14 angezeigt, im iobroker habe ich aber die 1.0.11 und bekomme kein Update angezeigt.

**Comment by Steff42** [comment]
Hallo @Kampfratte,
ist bekannt, da gibt es schon einen Issue (#36) dazu, bisher aber noch keine Lösung. Interessanterweise wird bei mir der Neujahrstag zweimal unter Objekte angezeigt. Einmal unter morgen und einmal unter übermorgen??
![image](https://user-images.githubusercontent.com/35137293/71616601-6a42e580-2bb7-11ea-8e32-69cf18d35f86.png)
Bei mir läuft die Version 1.0.14, die kannst Du über die Katze installieren.
Gruß Steffen

**Comment by Kampfratte** [comment]
Guten morgen Steffen,

wie über die Katze installieren? Wie geht das?

**Comment by Steff42** [comment]
Im ioBroker Tab Adapter auf das zweite Symbol von rechts klicken
![image](https://user-images.githubusercontent.com/35137293/71616904-dd009080-2bb8-11ea-881e-d8c60bc25530.png)
dann in dem sich öffnenden Fenster auf den Tab Beliebig klicken und die URL eingeben
![image](https://user-images.githubusercontent.com/35137293/71617079-a5461880-2bb9-11ea-8dcd-8dd65cc3917a.png)
dann unten auf installieren klicken und er sollte sich die neue Version ziehen.
So habe ich das immer gemacht.
Gruß Steffen

**Comment by Kampfratte** [comment]
danke, nun habe ich auch die 1.0.14... hab aber immer noch als nächster den 01.01.19 drin

**Comment by Steff42** [comment]
Ja klar, ist bei mir auch so. Wie schaut es bei dir bei den Objekten unter morgen und übermorgen aus?

**Comment by Pix---** [comment]
Hallo,
die Version 1.0.14 ist noch nicht im Stable-Repository (stabile Versionen), da sie noch nicht ausreichend getestet wurde. Erst wenn genügend Tester ein „Go“ geben, wird sie für alle Nutzer als Update angezeigt. 
Der Fehler „falsche Jahreszahl“ ist bekannt. Wenn zwischen dem heute-Datum und dem Feiertagsdatum ein Jahreswechsel liegt, muss das Jahr des Feiertags eins höher sein, als das jetzige Jahr. Da aber die Feiertag nicht als absolute Daten mit Jahreszahl hinterlegt werden, sondern berechnet werden, braucht es eine zusätzliche Abfrage. Bin bisher nicht zum Coden gekommen. Mitarbeit wird begrüßt :)

Guten Rutsch!
Pix

PS: morgen ist der Fehler nicht mehr sichtbar 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kampfratte** [comment]
Hallo Pix

mir war gerade mal ein bisschen langweilig und ich hab mir den Code mal genauer an gesehen. Hab bei mir in der main.js mal ein bisschen rum probiert und siehe da, da steht nun nächster Feiertag 01.01.20 *grins. Mal sehen, was morgen passiert. Ob dann beim nächsten Feiertag auch noch 20 steht oder ob da dann schon 21 steht

**Comment by Pix---** [comment]
Du kannst deine Code gern veröffentlichen. Nutze FORK, um dir eine Kopie des Adapters in deinen Github zu ziehen. Dann die Änderungen vornehmen und Pull request schicken.

Danke für die Mitarbeit.

Guten Rutsch noch!

**Comment by Kampfratte** [comment]
Ich habe das nun gemacht und hoffe, dass ich das auch richtig gemacht habe. War nämlich mein erstes mal.

**Comment by Kampfratte** [comment]
> Ja klar, ist bei mir auch so. Wie schaut es bei dir bei den Objekten unter morgen und übermorgen aus?

Steff42, da steht bei mir auch jeweils Neujahr und true drin. Aber da hab ich groß nie nach gesehen, da für mich in der Visualisierung nur der nächste Feiertag mit Anzahl der Tagen wichtig war.

**Comment by Pix---** [comment]
Danke an Kampfratte, habe den PR eingepflegt und Version 1.0.15zum test hier fertig gemacht. Wenn alles gut geht, kann ich die Version nächste Woche zu npm hochladen und somit für alle im stable freigeben.

**Comment by Kampfratte** [comment]
Gerne... musste das ganze gerade aber nochmal machen. Konnte die Datei vom Docker meiner Synology net runter ziehen, also schnell aussn Kopf die Datei nochmal geändert und tatsächlich ein Wort vergessen und gerade schnell rein gemacht.

**Comment by Kampfratte** [comment]
jesundes neues zusammen.
Es klappt. auch der nächste Feiertag bleibt bei 2020
