### ISSUE TITLE
Feiertage - Italien

### ISSUE THREAD

**Issue by martingarber** [Pix---/ioBroker.feiertage#52]
Hallo,

wäre es möglich folgende 2 italienische Feiertage hinzuzufügen:

25.04 - Tag der Befreiung (Liberazione Italia)
02.06 - Nationalfeiertag - Tag der Republik (Festa della Repubblica)

Vielen Dank im Voraus

lg

Martin

**Comment by Pix---** [comment]
Hallo Martin,
die neueste Version 1.0.18 kennt nun auch die genannten zwei Italienischen Feiertage.
Nach dem Test kann sie ins Stable.

Bleib gesund!

**Comment by martingarber** [comment]
Servus Pix,

vielen vielen Dank!!
Habe soeben den Adapter aktualisiert und werde dir evtl. Probleme mitteilen.

lg und bleib gesund.. und vor allem zuhause

Martin

Am Mi., 25. März 2020 um 23:02 Uhr schrieb Pix <notifications@github.com>:
