### ISSUE TITLE
Brückentage

### ISSUE THREAD

**Issue by Zwillingsvater** [Pix---/ioBroker.feiertage#56]
Hallo,

da Christi Himmelfahrt und Fronleichnam immer auf einen Donnerstag fallen, wäre es super, wenn man den Tag darauf als Brückentag auswählen könnte.
Könntet ihr diese beiden Tage verfügbar machen?

Vielen Dank im Voraus.

Gruß
Zwillingsvater

**Comment by Pix---** [comment]
Gute Idee und guter Einstieg in die Umsetzung der Brückentagsfunktion, die schon lange auf der Roadmap steht.
Werde erstmal händisch die Freitage nach Himmelfahrt, Fronleichnam und Weiberfastnacht aufnehmen.

Bisher spielt der Wochentag in der Berechnung der Feiertage keine Rolle. Mit `getDay()` sollte das ermitteln kein Problem sein. Allerdings muss dann mit dem nächsten Feiertag aus der Liste verglichen werden. Mache mir Gedanken ...

**Comment by Pix---** [comment]
Habe erstmal die betreffenden Brückentage manuell in die Liste eingefügt. Sie sind als "desc: bridge day" markiert. 
Es geht um die Freitage nach

- Weiberfastnacht (regional)
- Himmelfahrt
- Fronleichnam

Sie können nun in den Einstellungen als Feiertag ausgewählt werden.
Version 1.0.22
