### ISSUE TITLE
Sonderfeiertag in Berlin

### ISSUE THREAD

**Issue by Groej77** [Pix---/ioBroker.feiertage#60]
Hallo,

erstmal danke für den Adapter. Ich als Berliner hab einen Feiertag seit einiger Zeit den kein anderes Bundesland hat. Das wäre der internationale Frauentag der immer am 8. März ist. Könnte dieser noch eingepflegt werden?

MfG

Jörg

**Comment by Pix---** [comment]
Der Weltfrauentrag ist bereits vorhanden.
![Bildschirmfoto 2021-11-16 um 10 35 34](https://user-images.githubusercontent.com/8090989/141960097-d1de387d-eae3-4a94-81ac-e7d124169a66.jpg)

Gruß
Pix
